### ISSUE TITLE
Blank alloys can be mixed with standard.

### ISSUE THREAD

**Issue by MerrittK** [CannoliCatfish/project-rankine#198]
Alloys that lack nbt (because they are created via other mods), can be used interchangeably with custom alloyed metal, and the resulting tool inherits the custom metal, allowing the production of custom alloy tools at lower cost.

Since in 1.16 datapack recipes can no longer have nbt outputs, it would be nice to be able to use NBT-less alloys for default recipes without issue, since then rankine metals could be produced in other mod's machines.

**Comment by CannoliCatfish** [comment]
Thank you for your issue, and apologies for getting to it so late. Due to the upcoming new version, considering how our alloys fit into other mods has been to the forefront of our mind. 

NBT will still be present for our alloys, as it impacts the core of the alloying aspect of our mod and we have added recipe types which take advantage of them, but we also plan to make our alloys more compatible. For instance, since the general ratio for Bronze is 3 Copper - 1 Tin, default composition will now be switched to 75Cu-25Sn accordingly. We also have other related plans on how to handle more unique situations of alloy compositions from using other mods, and these changes will likely be introduced throughout the 1.3 versions of Project Rankine.
