### ISSUE TITLE
Client Crash with Alloy Template

### ISSUE THREAD

**Issue by yuesha-yc** [CannoliCatfish/project-rankine#209]
[crash-2021-08-08_19.45.40-client.txt](https://github.com/CannoliCatfish/project-rankine/files/6950739/crash-2021-08-08_19.45.40-client.txt)

**Comment by Reikona** [comment]
I have the same problem. The client is closed after hovering over the prepared template.
[crash-2021-08-18_06.54.07-client.txt](https://github.com/CannoliCatfish/project-rankine/files/7004468/crash-2021-08-18_06.54.07-client.txt)

**Comment by yuesha-yc** [comment]
I fixed it with mixin in my modpack. But I hope you can fix it so everyone gets the fix. 

https://github.com/TeamMoegMC/Frosted-Heart/blob/master/src/main/java/com/teammoeg/frostedheart/mixin/rankine/AlloyTemplateItemMixin.java#L57-L137

The problem here is that for some users that uses local languages like Chinese and Japanese, there are no "spaces" between words.  So splitting the translated strings with "space" causes this issue.

There is also a hidden bug in the addInformation method, I think you have referred to wrong indexes.

**Comment by CannoliCatfish** [comment]
Thank you for letting me know. I had figured out that the issue was related with the spacing and split array function, but I didn't realize it was due to other languages. I will merge the pull request in, but I will wait to close this and the reobf issue until the fix is actually released with the next major version (1.3) soon.
