### ISSUE TITLE
Gold Pan cooldown

### ISSUE THREAD

**Issue by KatoNamus** [CannoliCatfish/project-rankine#244]
Hi, could you please make the cooldown on the gold pans optional, even if enabled by default. It's a serious annoyance when trying to process a lot of loam quickly and should really not be forced. It's making me consider abandoning Project Rankine as it stands.

**Comment by CannoliCatfish** [comment]
Thank you for your suggestion! We can definitely accommodate for that option in our config file in the next update. We were also planning on changing the system so that different "recipes" (or blocks in this case) would have different cooldowns (so a harder material may take longer, early game materials are shorter, etc) when the feature is enabled. 

This issue will be closed when the config is added to the next version.

**Comment by KatoNamus** [comment]
Thank you very much. Sorry about about the whole "abandoning Project Rankine" grumpiness.

 If I may add to the suggestion; I am willing to wait for a material to cook up in a machine but don't like cooldowns on equipment. If you really have to time-gate higher tier activities or items, rather make it take some time to be made instead of taking time to be used. Case in point is these Wooden Gold Pans. Their durability is very low to start off with but it won't bother me to make e.g. 8 of them at a time, use them up (sans cooldown) and then make a few more. There is still a delay as I need to stop and make more Wooden Gold Pans but it doesn't feel as forced as when there's a cooldown. Waiting for a cooldown is just not fun while balancing your available equipment vs your available inventory space for products is quite a bit less hassle and feels less artificial/forced.

**Comment by CannoliCatfish** [comment]
This has been fixed as of Version 1.3.
